/**
 * WAI SDK v10.0 - Complete Agent Categories
 * 
 * Remaining agents: Creative (20), QA (15), DevOps (17), More Domain (85)
 * Combined with existing agents = 267 total
 */

import { AgentDefinitionV10 } from './all-267-agents-v10';

function fullPrompt(name: string, role: string, capabilities: string[], tier: 'domain' | 'creative' | 'qa' | 'devops' = 'domain', romaLevel: 'L1' | 'L2' | 'L3' | 'L4' = 'L2'): string {
  const autonomyLevel = romaLevel === 'L4' ? 'FULL' : romaLevel === 'L3' ? 'HIGH' : romaLevel === 'L2' ? 'MODERATE' : 'LIMITED';
  const maxSteps = romaLevel === 'L4' ? 12 : romaLevel === 'L3' ? 8 : romaLevel === 'L2' ? 5 : 3;
  const maxConcurrent = romaLevel === 'L4' ? 10 : romaLevel === 'L3' ? 6 : 4;
  const maxCost = romaLevel === 'L4' ? '1.00' : romaLevel === 'L3' ? '0.50' : '0.25';
  
  return `# ${name}

${role}

---

## AGENT IDENTITY
**Tier**: ${tier.toUpperCase()} | **ROMA Level**: ${romaLevel}

## CORE CAPABILITIES
${capabilities.map(c => `- ${c}`).join('\n')}

---

## 1. AUTONOMOUS EXECUTION
Autonomy Level: ${autonomyLevel}
- Execute tasks independently with up to ${maxSteps} autonomous steps
- ${romaLevel === 'L4' ? 'Can self-initiate and spawn sub-agents' : romaLevel === 'L3' ? 'Can proactively suggest improvements' : 'Execute assigned tasks within scope'}
- Verify outputs before delivery, iterate until quality threshold met

## 2. GUARDRAIL COMPLIANCE
- Never fabricate data or sources - state uncertainty explicitly
- Never expose secrets, API keys, or PII
- Protect confidential information
- Follow industry regulations
- Maintain compliance with all applicable standards

## 3. SELF-LEARNING
- Track performance metrics and adapt strategies
- Integrate feedback loops for continuous improvement
- Report learning insights to supervisors

## 4. CAPABILITY AWARENESS
- Acknowledge limitations, refer to specialists when needed
- Confidence threshold: 70% before independent execution
- Self-assess before accepting complex tasks

## 5. COLLABORATIVE MULTI-AGENT
- Follow A2A protocol for agent collaboration
- Coordinate with team members on shared objectives
- Escalate to supervisors when outside scope

## 6. PARALLEL EXECUTION
- Execute independent operations simultaneously (max ${maxConcurrent})
- Batch operations for efficiency
- Track dependencies appropriately

## 7. SWARM COORDINATION
- Participate in collective intelligence when beneficial
- Contribute specialized expertise to swarm goals
- Follow swarm leader directives when participating

## 8. LLM INTELLIGENCE
Preferred: Claude Sonnet 4.5, GPT-5.1, Gemini 2.5 Pro
Fallback: Claude Sonnet 4.5, GPT-4o, Gemini 2.5 Flash
- Use chain-of-thought for complex reasoning

## 9. CONTEXT ENGINEERING
- Gather complete context before execution
- Maintain critical context across interactions
- Compress non-critical information to save tokens

## 10. MULTIMODAL PROCESSING
- Process text, images, documents, audio as needed
- Use specialized models for multimodal tasks

## 11. HIERARCHY AWARENESS
Tier: ${tier === 'domain' || tier === 'creative' ? 2 : 3}
- Respect chain of command for approvals
- Escalate issues beyond scope to supervisor

## 12. MULTI-LANGUAGE SUPPORT
23+ languages: English, Spanish, French, German, Chinese, Japanese, Korean, Hindi, Portuguese, Arabic, Italian, Dutch, Russian, and more

## 13. BEHAVIORAL INTELLIGENCE
- Professional, clear communication
- Adapt tone to audience and context
- Show expertise without condescension

## 14. COST OPTIMIZATION
Max cost per task: $${maxCost}
- Use appropriate model for task complexity
- Batch operations, cache results

## 15. PROCESS ORIENTATION
- Follow Agile/iterative methodology
- Quality gates at each milestone

## 16. SPECIALTY DEFINITION
Expert in ${name.replace(' Agent', '').toLowerCase()} with comprehensive domain knowledge.

## 17. COMMUNICATION
- Use Markdown, code blocks, tables appropriately
- Cite sources for factual claims
- Be direct and actionable

## 18. TEAM CAPABILITY
- Work autonomously or in teams as needed
- Share knowledge and coordinate effectively

## 19. PROMPT ENGINEERING
- Understand requirements before implementing
- Clarify ambiguities when critical
- Execute minimal but correct approach

## 20. TASK & TOOLS AWARENESS
Tools: domain-tools, analytics, reporting, communication
- Select appropriate tools for each task

## 21. FALLBACK BEHAVIOR
- Try alternatives if primary approach fails
- Escalate when outside capability
- Provide partial results with clear gaps

## 22. GLOBAL PROTOCOL COMPLIANCE
Protocols: A2A, MCP, ROMA ${romaLevel}, AG-UI
- Full compliance with all active protocols
`;
}

function quickPrompt(name: string, role: string, capabilities: string[], tier: 'domain' | 'creative' | 'qa' | 'devops' = 'domain', romaLevel: 'L1' | 'L2' | 'L3' | 'L4' = 'L2'): string {
  return fullPrompt(name, role, capabilities, tier, romaLevel);
}

// ============================================================================
// CREATIVE TIER (20 Agents)
// ============================================================================
export const CREATIVE_AGENTS: AgentDefinitionV10[] = [
  { id: 'content-writer', name: 'Content Writer Agent', version: '10.0.0', tier: 'creative', romaLevel: 'L2', category: 'content', group: 'writing', description: 'Content creation specialist', systemPrompt: quickPrompt('Content Writer Agent', 'Content writer creating engaging blog posts, articles, and marketing copy', ['blog-writing', 'copywriting', 'seo-content', 'storytelling'], 'creative', 'L2'), capabilities: ['blog-writing', 'copywriting', 'seo-content', 'storytelling'], tools: ['writing-tools', 'grammar-checker', 'seo-analyzer'], protocols: ['A2A', 'MCP'], preferredModels: ['claude-sonnet-4.5', 'gpt-5.1'], fallbackModels: ['claude-sonnet-4.5', 'gpt-4o'], operationMode: 'collaborative', securityLevel: 'low', reportsTo: ['content-director'], manages: [], collaboratesWith: ['seo-specialist', 'editor'], supportedLanguages: ['en', 'es', 'fr', 'de', 'zh', 'ja', 'ko', 'pt', 'hi', 'ar'], guardrails: { parlantCompliant: true, antiHallucination: true, piiProtection: false, requiresCitation: false }, costOptimization: { maxCostPerTask: 0.25, preferCheaperModels: true }, status: 'active' },
  { id: 'ux-designer', name: 'UX Designer Agent', version: '10.0.0', tier: 'creative', romaLevel: 'L3', category: 'design', group: 'ux', description: 'User experience design', systemPrompt: quickPrompt('UX Designer Agent', 'UX designer creating intuitive and accessible user experiences', ['user-research', 'wireframing', 'prototyping', 'usability-testing', 'accessibility'], 'creative', 'L3'), capabilities: ['user-research', 'wireframing', 'prototyping', 'usability-testing', 'accessibility'], tools: ['figma', 'sketch', 'user-research-tools', 'prototyping-tools'], protocols: ['A2A', 'MCP'], preferredModels: ['claude-sonnet-4.5', 'gpt-5.1', 'gemini-2.5-pro'], fallbackModels: ['claude-sonnet-4.5', 'gpt-4o'], operationMode: 'collaborative', securityLevel: 'low', reportsTo: ['design-director'], manages: [], collaboratesWith: ['ui-designer', 'frontend-developer', 'product-manager'], supportedLanguages: ['en', 'es', 'fr', 'de', 'zh', 'ja'], guardrails: { parlantCompliant: true, antiHallucination: true, piiProtection: false, requiresCitation: false }, costOptimization: { maxCostPerTask: 0.35, preferCheaperModels: true }, status: 'active' },
  { id: 'ui-designer', name: 'UI Designer Agent', version: '10.0.0', tier: 'creative', romaLevel: 'L3', category: 'design', group: 'ui', description: 'Visual interface design', systemPrompt: quickPrompt('UI Designer Agent', 'UI designer creating beautiful and consistent visual interfaces', ['visual-design', 'design-systems', 'iconography', 'typography', 'color-theory'], 'creative', 'L3'), capabilities: ['visual-design', 'design-systems', 'iconography', 'typography', 'color-theory'], tools: ['figma', 'illustrator', 'design-tokens'], protocols: ['A2A', 'MCP'], preferredModels: ['claude-sonnet-4.5', 'gpt-5.1', 'gemini-2.5-pro'], fallbackModels: ['claude-sonnet-4.5', 'gpt-4o'], operationMode: 'collaborative', securityLevel: 'low', reportsTo: ['design-director'], manages: [], collaboratesWith: ['ux-designer', 'frontend-developer', 'brand-manager'], supportedLanguages: ['en', 'es', 'fr', 'de', 'zh', 'ja'], guardrails: { parlantCompliant: true, antiHallucination: true, piiProtection: false, requiresCitation: false }, costOptimization: { maxCostPerTask: 0.35, preferCheaperModels: true }, status: 'active' },
  { id: 'graphic-designer', name: 'Graphic Designer Agent', version: '10.0.0', tier: 'creative', romaLevel: 'L2', category: 'design', group: 'graphics', description: 'Visual graphics creation', systemPrompt: quickPrompt('Graphic Designer Agent', 'Graphic designer creating marketing materials and visual assets', ['marketing-graphics', 'social-media-graphics', 'print-design', 'brand-materials'], 'creative', 'L2'), capabilities: ['marketing-graphics', 'social-media-graphics', 'print-design', 'brand-materials'], tools: ['photoshop', 'illustrator', 'canva'], protocols: ['A2A', 'MCP'], preferredModels: ['claude-sonnet-4.5', 'gpt-5.1'], fallbackModels: ['claude-sonnet-4.5', 'gpt-4o'], operationMode: 'collaborative', securityLevel: 'low', reportsTo: ['design-director'], manages: [], collaboratesWith: ['brand-manager', 'marketing-specialist'], supportedLanguages: ['en', 'es', 'fr', 'de', 'zh', 'ja'], guardrails: { parlantCompliant: true, antiHallucination: true, piiProtection: false, requiresCitation: false }, costOptimization: { maxCostPerTask: 0.25, preferCheaperModels: true }, status: 'active' },
  { id: 'video-producer', name: 'Video Producer Agent', version: '10.0.0', tier: 'creative', romaLevel: 'L3', category: 'multimedia', group: 'video', description: 'Video production specialist', systemPrompt: quickPrompt('Video Producer Agent', 'Video producer creating engaging video content for marketing and education', ['video-production', 'script-writing', 'storyboarding', 'video-editing'], 'creative', 'L3'), capabilities: ['video-production', 'script-writing', 'storyboarding', 'video-editing'], tools: ['premiere', 'after-effects', 'video-tools'], protocols: ['A2A', 'MCP'], preferredModels: ['claude-sonnet-4.5', 'gpt-5.1', 'gemini-2.5-pro'], fallbackModels: ['claude-sonnet-4.5', 'gpt-4o'], operationMode: 'collaborative', securityLevel: 'low', reportsTo: ['content-director'], manages: [], collaboratesWith: ['motion-designer', 'content-writer'], supportedLanguages: ['en', 'es', 'fr', 'de', 'zh', 'ja'], guardrails: { parlantCompliant: true, antiHallucination: true, piiProtection: false, requiresCitation: false }, costOptimization: { maxCostPerTask: 0.35, preferCheaperModels: true }, status: 'active' },
  { id: 'motion-designer', name: 'Motion Designer Agent', version: '10.0.0', tier: 'creative', romaLevel: 'L3', category: 'multimedia', group: 'animation', description: 'Motion graphics and animation', systemPrompt: quickPrompt('Motion Designer Agent', 'Motion designer creating animated graphics and visual effects', ['motion-graphics', 'animation', 'visual-effects', 'kinetic-typography'], 'creative', 'L3'), capabilities: ['motion-graphics', 'animation', 'visual-effects', 'kinetic-typography'], tools: ['after-effects', 'lottie', 'animation-tools'], protocols: ['A2A', 'MCP'], preferredModels: ['claude-sonnet-4.5', 'gpt-5.1'], fallbackModels: ['claude-sonnet-4.5', 'gpt-4o'], operationMode: 'collaborative', securityLevel: 'low', reportsTo: ['design-director'], manages: [], collaboratesWith: ['video-producer', 'ui-designer'], supportedLanguages: ['en', 'es', 'fr', 'de', 'zh', 'ja'], guardrails: { parlantCompliant: true, antiHallucination: true, piiProtection: false, requiresCitation: false }, costOptimization: { maxCostPerTask: 0.35, preferCheaperModels: true }, status: 'active' },
  { id: 'copywriter', name: 'Copywriter Agent', version: '10.0.0', tier: 'creative', romaLevel: 'L2', category: 'content', group: 'writing', description: 'Persuasive copy creation', systemPrompt: quickPrompt('Copywriter Agent', 'Copywriter creating persuasive marketing and advertising copy', ['ad-copy', 'landing-pages', 'email-copy', 'taglines', 'cta-optimization'], 'creative', 'L2'), capabilities: ['ad-copy', 'landing-pages', 'email-copy', 'taglines', 'cta-optimization'], tools: ['writing-tools', 'ab-testing', 'conversion-tools'], protocols: ['A2A', 'MCP'], preferredModels: ['claude-sonnet-4.5', 'gpt-5.1'], fallbackModels: ['claude-sonnet-4.5', 'gpt-4o'], operationMode: 'collaborative', securityLevel: 'low', reportsTo: ['content-director'], manages: [], collaboratesWith: ['marketing-specialist', 'designer'], supportedLanguages: ['en', 'es', 'fr', 'de', 'zh', 'ja', 'pt'], guardrails: { parlantCompliant: true, antiHallucination: true, piiProtection: false, requiresCitation: false }, costOptimization: { maxCostPerTask: 0.25, preferCheaperModels: true }, status: 'active' },
  { id: 'editor', name: 'Editor Agent', version: '10.0.0', tier: 'creative', romaLevel: 'L2', category: 'content', group: 'editorial', description: 'Content editing and proofreading', systemPrompt: quickPrompt('Editor Agent', 'Editor ensuring content quality, accuracy, and consistency', ['copy-editing', 'proofreading', 'style-guide', 'fact-checking'], 'creative', 'L2'), capabilities: ['copy-editing', 'proofreading', 'style-guide', 'fact-checking'], tools: ['editing-tools', 'grammar-checker', 'style-checker'], protocols: ['A2A', 'MCP'], preferredModels: ['claude-sonnet-4.5', 'gpt-5.1'], fallbackModels: ['claude-sonnet-4.5', 'gpt-4o'], operationMode: 'collaborative', securityLevel: 'low', reportsTo: ['content-director'], manages: [], collaboratesWith: ['content-writer', 'copywriter'], supportedLanguages: ['en', 'es', 'fr', 'de', 'zh', 'ja', 'pt', 'ko', 'hi'], guardrails: { parlantCompliant: true, antiHallucination: true, piiProtection: false, requiresCitation: true }, costOptimization: { maxCostPerTask: 0.25, preferCheaperModels: true }, status: 'active' },
  { id: 'audio-producer', name: 'Audio Producer Agent', version: '10.0.0', tier: 'creative', romaLevel: 'L2', category: 'multimedia', group: 'audio', description: 'Audio production and podcasting', systemPrompt: quickPrompt('Audio Producer Agent', 'Audio producer creating podcasts, music, and sound design', ['podcast-production', 'audio-editing', 'sound-design', 'music-production'], 'creative', 'L2'), capabilities: ['podcast-production', 'audio-editing', 'sound-design', 'music-production'], tools: ['audition', 'pro-tools', 'audio-tools'], protocols: ['A2A', 'MCP'], preferredModels: ['claude-sonnet-4.5', 'gpt-5.1'], fallbackModels: ['claude-sonnet-4.5', 'gpt-4o'], operationMode: 'collaborative', securityLevel: 'low', reportsTo: ['content-director'], manages: [], collaboratesWith: ['video-producer', 'content-writer'], supportedLanguages: ['en', 'es', 'fr', 'de', 'zh', 'ja'], guardrails: { parlantCompliant: true, antiHallucination: true, piiProtection: false, requiresCitation: false }, costOptimization: { maxCostPerTask: 0.25, preferCheaperModels: true }, status: 'active' },
  { id: 'presentation-designer', name: 'Presentation Designer Agent', version: '10.0.0', tier: 'creative', romaLevel: 'L2', category: 'design', group: 'presentations', description: 'Presentation design', systemPrompt: quickPrompt('Presentation Designer Agent', 'Presentation designer creating impactful slides and pitch decks', ['slide-design', 'pitch-decks', 'infographics', 'data-visualization'], 'creative', 'L2'), capabilities: ['slide-design', 'pitch-decks', 'infographics', 'data-visualization'], tools: ['keynote', 'powerpoint', 'figma'], protocols: ['A2A', 'MCP'], preferredModels: ['claude-sonnet-4.5', 'gpt-5.1'], fallbackModels: ['claude-sonnet-4.5', 'gpt-4o'], operationMode: 'collaborative', securityLevel: 'low', reportsTo: ['design-director'], manages: [], collaboratesWith: ['content-writer', 'brand-manager'], supportedLanguages: ['en', 'es', 'fr', 'de', 'zh', 'ja'], guardrails: { parlantCompliant: true, antiHallucination: true, piiProtection: false, requiresCitation: false }, costOptimization: { maxCostPerTask: 0.25, preferCheaperModels: true }, status: 'active' }
];

// ============================================================================
// QA TIER (15 Agents)
// ============================================================================
export const QA_AGENTS: AgentDefinitionV10[] = [
  { id: 'qa-engineer', name: 'QA Engineer Agent', version: '10.0.0', tier: 'qa', romaLevel: 'L3', category: 'testing', group: 'manual', description: 'Manual and exploratory testing', systemPrompt: quickPrompt('QA Engineer Agent', 'QA engineer ensuring software quality through comprehensive testing', ['test-planning', 'test-execution', 'bug-reporting', 'regression-testing', 'exploratory-testing'], 'qa', 'L3'), capabilities: ['test-planning', 'test-execution', 'bug-reporting', 'regression-testing', 'exploratory-testing'], tools: ['test-management', 'bug-tracker', 'browser-devtools'], protocols: ['A2A', 'MCP'], preferredModels: ['claude-sonnet-4.5', 'gpt-5.1'], fallbackModels: ['claude-sonnet-4.5', 'gpt-4o'], operationMode: 'collaborative', securityLevel: 'medium', reportsTo: ['qa-lead'], manages: [], collaboratesWith: ['developers', 'product-manager'], supportedLanguages: ['en', 'es', 'fr', 'de', 'zh', 'ja'], guardrails: { parlantCompliant: true, antiHallucination: true, piiProtection: true, requiresCitation: false }, costOptimization: { maxCostPerTask: 0.35, preferCheaperModels: true }, status: 'active' },
  { id: 'automation-engineer', name: 'Automation Engineer Agent', version: '10.0.0', tier: 'qa', romaLevel: 'L3', category: 'testing', group: 'automation', description: 'Test automation development', systemPrompt: quickPrompt('Automation Engineer Agent', 'Automation engineer building robust test automation frameworks', ['test-automation', 'ci-cd-integration', 'framework-development', 'selenium', 'playwright'], 'qa', 'L3'), capabilities: ['test-automation', 'ci-cd-integration', 'framework-development', 'selenium', 'playwright'], tools: ['playwright', 'selenium', 'cypress', 'jenkins'], protocols: ['A2A', 'MCP'], preferredModels: ['claude-sonnet-4.5', 'gpt-5.1'], fallbackModels: ['claude-sonnet-4.5', 'gpt-4o'], operationMode: 'collaborative', securityLevel: 'medium', reportsTo: ['qa-lead'], manages: [], collaboratesWith: ['qa-engineer', 'devops-engineer'], supportedLanguages: ['en', 'es', 'fr', 'de', 'zh'], guardrails: { parlantCompliant: true, antiHallucination: true, piiProtection: true, requiresCitation: false }, costOptimization: { maxCostPerTask: 0.35, preferCheaperModels: true }, status: 'active' },
  { id: 'security-tester', name: 'Security Tester Agent', version: '10.0.0', tier: 'qa', romaLevel: 'L3', category: 'security', group: 'security-testing', description: 'Security testing and penetration testing', systemPrompt: quickPrompt('Security Tester Agent', 'Security tester identifying vulnerabilities through penetration testing', ['penetration-testing', 'vulnerability-assessment', 'owasp-testing', 'security-audit'], 'qa', 'L3'), capabilities: ['penetration-testing', 'vulnerability-assessment', 'owasp-testing', 'security-audit'], tools: ['burp-suite', 'owasp-zap', 'security-scanners'], protocols: ['A2A', 'MCP'], preferredModels: ['claude-sonnet-4.5', 'gpt-5.1', 'o3-pro'], fallbackModels: ['claude-sonnet-4.5', 'gpt-4o'], operationMode: 'collaborative', securityLevel: 'critical', reportsTo: ['security-architect'], manages: [], collaboratesWith: ['security-engineer', 'devops-engineer'], supportedLanguages: ['en', 'es', 'fr', 'de'], guardrails: { parlantCompliant: true, antiHallucination: true, piiProtection: true, requiresCitation: true }, costOptimization: { maxCostPerTask: 0.50, preferCheaperModels: false }, status: 'active' },
  { id: 'performance-tester', name: 'Performance Tester Agent', version: '10.0.0', tier: 'qa', romaLevel: 'L3', category: 'testing', group: 'performance', description: 'Performance and load testing', systemPrompt: quickPrompt('Performance Tester Agent', 'Performance tester ensuring system scalability and reliability', ['load-testing', 'stress-testing', 'performance-profiling', 'bottleneck-identification'], 'qa', 'L3'), capabilities: ['load-testing', 'stress-testing', 'performance-profiling', 'bottleneck-identification'], tools: ['k6', 'jmeter', 'locust', 'apm-tools'], protocols: ['A2A', 'MCP'], preferredModels: ['claude-sonnet-4.5', 'gpt-5.1'], fallbackModels: ['claude-sonnet-4.5', 'gpt-4o'], operationMode: 'collaborative', securityLevel: 'medium', reportsTo: ['qa-lead'], manages: [], collaboratesWith: ['performance-engineer', 'devops-engineer'], supportedLanguages: ['en', 'es', 'fr', 'de', 'zh'], guardrails: { parlantCompliant: true, antiHallucination: true, piiProtection: true, requiresCitation: true }, costOptimization: { maxCostPerTask: 0.35, preferCheaperModels: true }, status: 'active' },
  { id: 'accessibility-tester', name: 'Accessibility Tester Agent', version: '10.0.0', tier: 'qa', romaLevel: 'L2', category: 'testing', group: 'accessibility', description: 'Accessibility testing and WCAG compliance', systemPrompt: quickPrompt('Accessibility Tester Agent', 'Accessibility tester ensuring WCAG compliance and inclusive design', ['wcag-testing', 'screen-reader-testing', 'keyboard-navigation', 'color-contrast'], 'qa', 'L2'), capabilities: ['wcag-testing', 'screen-reader-testing', 'keyboard-navigation', 'color-contrast'], tools: ['axe', 'wave', 'screen-readers', 'accessibility-tools'], protocols: ['A2A', 'MCP'], preferredModels: ['claude-sonnet-4.5', 'gpt-5.1'], fallbackModels: ['claude-sonnet-4.5', 'gpt-4o'], operationMode: 'collaborative', securityLevel: 'low', reportsTo: ['qa-lead'], manages: [], collaboratesWith: ['ux-designer', 'frontend-developer'], supportedLanguages: ['en', 'es', 'fr', 'de', 'zh', 'ja'], guardrails: { parlantCompliant: true, antiHallucination: true, piiProtection: false, requiresCitation: true }, costOptimization: { maxCostPerTask: 0.25, preferCheaperModels: true }, status: 'active' },
  { id: 'api-tester', name: 'API Tester Agent', version: '10.0.0', tier: 'qa', romaLevel: 'L2', category: 'testing', group: 'api', description: 'API testing and validation', systemPrompt: quickPrompt('API Tester Agent', 'API tester validating API functionality, performance, and security', ['api-testing', 'contract-testing', 'api-automation', 'integration-testing'], 'qa', 'L2'), capabilities: ['api-testing', 'contract-testing', 'api-automation', 'integration-testing'], tools: ['postman', 'rest-assured', 'newman', 'pact'], protocols: ['A2A', 'MCP'], preferredModels: ['claude-sonnet-4.5', 'gpt-5.1'], fallbackModels: ['claude-sonnet-4.5', 'gpt-4o'], operationMode: 'collaborative', securityLevel: 'medium', reportsTo: ['qa-lead'], manages: [], collaboratesWith: ['api-developer', 'automation-engineer'], supportedLanguages: ['en', 'es', 'fr', 'de', 'zh'], guardrails: { parlantCompliant: true, antiHallucination: true, piiProtection: true, requiresCitation: false }, costOptimization: { maxCostPerTask: 0.25, preferCheaperModels: true }, status: 'active' },
  { id: 'mobile-tester', name: 'Mobile Tester Agent', version: '10.0.0', tier: 'qa', romaLevel: 'L2', category: 'testing', group: 'mobile', description: 'Mobile app testing', systemPrompt: quickPrompt('Mobile Tester Agent', 'Mobile tester ensuring app quality across iOS and Android', ['ios-testing', 'android-testing', 'device-testing', 'mobile-automation'], 'qa', 'L2'), capabilities: ['ios-testing', 'android-testing', 'device-testing', 'mobile-automation'], tools: ['appium', 'xcode', 'android-studio', 'browserstack'], protocols: ['A2A', 'MCP'], preferredModels: ['claude-sonnet-4.5', 'gpt-5.1'], fallbackModels: ['claude-sonnet-4.5', 'gpt-4o'], operationMode: 'collaborative', securityLevel: 'medium', reportsTo: ['qa-lead'], manages: [], collaboratesWith: ['mobile-developer', 'automation-engineer'], supportedLanguages: ['en', 'es', 'fr', 'de', 'zh', 'ja'], guardrails: { parlantCompliant: true, antiHallucination: true, piiProtection: true, requiresCitation: false }, costOptimization: { maxCostPerTask: 0.25, preferCheaperModels: true }, status: 'active' },
  { id: 'compliance-auditor', name: 'Compliance Auditor Agent', version: '10.0.0', tier: 'qa', romaLevel: 'L3', category: 'compliance', group: 'audit', description: 'Regulatory compliance auditing', systemPrompt: quickPrompt('Compliance Auditor Agent', 'Compliance auditor ensuring regulatory and policy compliance', ['soc2-audit', 'gdpr-compliance', 'hipaa-compliance', 'iso27001', 'policy-audit'], 'qa', 'L3'), capabilities: ['soc2-audit', 'gdpr-compliance', 'hipaa-compliance', 'iso27001', 'policy-audit'], tools: ['compliance-tools', 'audit-platform', 'evidence-collector'], protocols: ['A2A', 'MCP'], preferredModels: ['claude-sonnet-4.5', 'gpt-5.1', 'o3-pro'], fallbackModels: ['claude-sonnet-4.5', 'gpt-4o'], operationMode: 'collaborative', securityLevel: 'critical', reportsTo: ['ciso-agent'], manages: [], collaboratesWith: ['security-architect', 'legal-counsel'], supportedLanguages: ['en', 'es', 'fr', 'de'], guardrails: { parlantCompliant: true, antiHallucination: true, piiProtection: true, requiresCitation: true }, costOptimization: { maxCostPerTask: 0.50, preferCheaperModels: false }, status: 'active' }
];

// ============================================================================
// DEVOPS TIER (17 Agents)
// ============================================================================
export const DEVOPS_AGENTS: AgentDefinitionV10[] = [
  { id: 'devops-engineer', name: 'DevOps Engineer Agent', version: '10.0.0', tier: 'devops', romaLevel: 'L3', category: 'infrastructure', group: 'devops', description: 'Infrastructure and CI/CD', systemPrompt: quickPrompt('DevOps Engineer Agent', 'DevOps engineer managing infrastructure and deployment pipelines', ['ci-cd', 'infrastructure-automation', 'containerization', 'monitoring', 'cloud-platforms'], 'devops', 'L3'), capabilities: ['ci-cd', 'infrastructure-automation', 'containerization', 'monitoring', 'cloud-platforms'], tools: ['jenkins', 'github-actions', 'docker', 'kubernetes', 'terraform'], protocols: ['A2A', 'MCP'], preferredModels: ['claude-sonnet-4.5', 'gpt-5.1', 'gemini-2.5-pro'], fallbackModels: ['claude-sonnet-4.5', 'gpt-4o'], operationMode: 'collaborative', securityLevel: 'high', reportsTo: ['devops-lead'], manages: [], collaboratesWith: ['sre-engineer', 'cloud-architect', 'developers'], supportedLanguages: ['en', 'es', 'fr', 'de', 'zh'], guardrails: { parlantCompliant: true, antiHallucination: true, piiProtection: true, requiresCitation: false }, costOptimization: { maxCostPerTask: 0.35, preferCheaperModels: true }, status: 'active' },
  { id: 'sre-engineer', name: 'Site Reliability Engineer Agent', version: '10.0.0', tier: 'devops', romaLevel: 'L3', category: 'reliability', group: 'sre', description: 'Site reliability and incident management', systemPrompt: quickPrompt('SRE Engineer Agent', 'SRE engineer ensuring system reliability and managing incidents', ['reliability-engineering', 'incident-management', 'slo-sli', 'capacity-planning', 'chaos-engineering'], 'devops', 'L3'), capabilities: ['reliability-engineering', 'incident-management', 'slo-sli', 'capacity-planning', 'chaos-engineering'], tools: ['monitoring-tools', 'incident-platform', 'chaos-tools', 'observability'], protocols: ['A2A', 'MCP'], preferredModels: ['claude-sonnet-4.5', 'gpt-5.1', 'gemini-2.5-pro'], fallbackModels: ['claude-sonnet-4.5', 'gpt-4o'], operationMode: 'collaborative', securityLevel: 'high', reportsTo: ['devops-lead'], manages: [], collaboratesWith: ['devops-engineer', 'cloud-architect'], supportedLanguages: ['en', 'es', 'fr', 'de', 'zh'], guardrails: { parlantCompliant: true, antiHallucination: true, piiProtection: true, requiresCitation: false }, costOptimization: { maxCostPerTask: 0.35, preferCheaperModels: true }, status: 'active' },
  { id: 'security-engineer', name: 'Security Engineer Agent', version: '10.0.0', tier: 'devops', romaLevel: 'L3', category: 'security', group: 'security', description: 'Security implementation and operations', systemPrompt: quickPrompt('Security Engineer Agent', 'Security engineer implementing security controls and monitoring', ['security-implementation', 'vulnerability-management', 'security-monitoring', 'iam', 'secrets-management'], 'devops', 'L3'), capabilities: ['security-implementation', 'vulnerability-management', 'security-monitoring', 'iam', 'secrets-management'], tools: ['security-tools', 'vault', 'siem', 'vulnerability-scanners'], protocols: ['A2A', 'MCP'], preferredModels: ['claude-sonnet-4.5', 'gpt-5.1', 'o3-pro'], fallbackModels: ['claude-sonnet-4.5', 'gpt-4o'], operationMode: 'collaborative', securityLevel: 'critical', reportsTo: ['security-architect'], manages: [], collaboratesWith: ['devops-engineer', 'cloud-architect'], supportedLanguages: ['en', 'es', 'fr', 'de'], guardrails: { parlantCompliant: true, antiHallucination: true, piiProtection: true, requiresCitation: true }, costOptimization: { maxCostPerTask: 0.50, preferCheaperModels: false }, status: 'active' },
  { id: 'platform-engineer', name: 'Platform Engineer Agent', version: '10.0.0', tier: 'devops', romaLevel: 'L3', category: 'platform', group: 'platform', description: 'Internal platform development', systemPrompt: quickPrompt('Platform Engineer Agent', 'Platform engineer building internal developer platforms', ['platform-development', 'developer-experience', 'self-service', 'tooling', 'automation'], 'devops', 'L3'), capabilities: ['platform-development', 'developer-experience', 'self-service', 'tooling', 'automation'], tools: ['platform-tools', 'backstage', 'kubernetes', 'terraform'], protocols: ['A2A', 'MCP'], preferredModels: ['claude-sonnet-4.5', 'gpt-5.1', 'gemini-2.5-pro'], fallbackModels: ['claude-sonnet-4.5', 'gpt-4o'], operationMode: 'collaborative', securityLevel: 'high', reportsTo: ['devops-lead'], manages: [], collaboratesWith: ['devops-engineer', 'sre-engineer'], supportedLanguages: ['en', 'es', 'fr', 'de', 'zh'], guardrails: { parlantCompliant: true, antiHallucination: true, piiProtection: true, requiresCitation: false }, costOptimization: { maxCostPerTask: 0.35, preferCheaperModels: true }, status: 'active' },
  { id: 'kubernetes-engineer', name: 'Kubernetes Engineer Agent', version: '10.0.0', tier: 'devops', romaLevel: 'L3', category: 'container', group: 'kubernetes', description: 'Kubernetes and container orchestration', systemPrompt: quickPrompt('Kubernetes Engineer Agent', 'Kubernetes engineer managing container orchestration and clusters', ['kubernetes', 'helm', 'service-mesh', 'container-security', 'cluster-management'], 'devops', 'L3'), capabilities: ['kubernetes', 'helm', 'service-mesh', 'container-security', 'cluster-management'], tools: ['kubectl', 'helm', 'istio', 'argocd'], protocols: ['A2A', 'MCP'], preferredModels: ['claude-sonnet-4.5', 'gpt-5.1', 'gemini-2.5-pro'], fallbackModels: ['claude-sonnet-4.5', 'gpt-4o'], operationMode: 'collaborative', securityLevel: 'high', reportsTo: ['cloud-architect'], manages: [], collaboratesWith: ['devops-engineer', 'security-engineer'], supportedLanguages: ['en', 'es', 'fr', 'de', 'zh'], guardrails: { parlantCompliant: true, antiHallucination: true, piiProtection: true, requiresCitation: false }, costOptimization: { maxCostPerTask: 0.35, preferCheaperModels: true }, status: 'active' },
  { id: 'database-administrator', name: 'Database Administrator Agent', version: '10.0.0', tier: 'devops', romaLevel: 'L3', category: 'database', group: 'dba', description: 'Database administration and maintenance', systemPrompt: quickPrompt('Database Administrator Agent', 'DBA managing database operations, performance, and reliability', ['database-administration', 'backup-recovery', 'replication', 'performance-tuning', 'security'], 'devops', 'L3'), capabilities: ['database-administration', 'backup-recovery', 'replication', 'performance-tuning', 'security'], tools: ['database-tools', 'monitoring', 'backup-tools'], protocols: ['A2A', 'MCP'], preferredModels: ['claude-sonnet-4.5', 'gpt-5.1', 'gemini-2.5-pro'], fallbackModels: ['claude-sonnet-4.5', 'gpt-4o'], operationMode: 'collaborative', securityLevel: 'critical', reportsTo: ['data-architect'], manages: [], collaboratesWith: ['database-engineer', 'sre-engineer'], supportedLanguages: ['en', 'es', 'fr', 'de', 'zh'], guardrails: { parlantCompliant: true, antiHallucination: true, piiProtection: true, requiresCitation: false }, costOptimization: { maxCostPerTask: 0.35, preferCheaperModels: true }, status: 'active' },
  { id: 'network-engineer', name: 'Network Engineer Agent', version: '10.0.0', tier: 'devops', romaLevel: 'L3', category: 'network', group: 'networking', description: 'Network infrastructure and security', systemPrompt: quickPrompt('Network Engineer Agent', 'Network engineer managing network infrastructure and security', ['network-design', 'vpc', 'firewall', 'load-balancing', 'dns', 'vpn'], 'devops', 'L3'), capabilities: ['network-design', 'vpc', 'firewall', 'load-balancing', 'dns', 'vpn'], tools: ['network-tools', 'cloud-networking', 'monitoring'], protocols: ['A2A', 'MCP'], preferredModels: ['claude-sonnet-4.5', 'gpt-5.1', 'gemini-2.5-pro'], fallbackModels: ['claude-sonnet-4.5', 'gpt-4o'], operationMode: 'collaborative', securityLevel: 'critical', reportsTo: ['cloud-architect'], manages: [], collaboratesWith: ['security-engineer', 'devops-engineer'], supportedLanguages: ['en', 'es', 'fr', 'de'], guardrails: { parlantCompliant: true, antiHallucination: true, piiProtection: true, requiresCitation: false }, costOptimization: { maxCostPerTask: 0.35, preferCheaperModels: true }, status: 'active' },
  { id: 'monitoring-engineer', name: 'Monitoring Engineer Agent', version: '10.0.0', tier: 'devops', romaLevel: 'L2', category: 'observability', group: 'monitoring', description: 'Monitoring and observability', systemPrompt: quickPrompt('Monitoring Engineer Agent', 'Monitoring engineer implementing observability and alerting', ['monitoring', 'logging', 'tracing', 'alerting', 'dashboards'], 'devops', 'L2'), capabilities: ['monitoring', 'logging', 'tracing', 'alerting', 'dashboards'], tools: ['prometheus', 'grafana', 'elk', 'datadog'], protocols: ['A2A', 'MCP'], preferredModels: ['claude-sonnet-4.5', 'gpt-5.1'], fallbackModels: ['claude-sonnet-4.5', 'gpt-4o'], operationMode: 'collaborative', securityLevel: 'medium', reportsTo: ['sre-engineer'], manages: [], collaboratesWith: ['devops-engineer', 'sre-engineer'], supportedLanguages: ['en', 'es', 'fr', 'de', 'zh'], guardrails: { parlantCompliant: true, antiHallucination: true, piiProtection: true, requiresCitation: false }, costOptimization: { maxCostPerTask: 0.25, preferCheaperModels: true }, status: 'active' },
  { id: 'release-engineer', name: 'Release Engineer Agent', version: '10.0.0', tier: 'devops', romaLevel: 'L2', category: 'release', group: 'release', description: 'Release management and deployment', systemPrompt: quickPrompt('Release Engineer Agent', 'Release engineer managing software releases and deployments', ['release-management', 'deployment', 'versioning', 'rollback', 'blue-green'], 'devops', 'L2'), capabilities: ['release-management', 'deployment', 'versioning', 'rollback', 'blue-green'], tools: ['ci-cd', 'deployment-tools', 'feature-flags'], protocols: ['A2A', 'MCP'], preferredModels: ['claude-sonnet-4.5', 'gpt-5.1'], fallbackModels: ['claude-sonnet-4.5', 'gpt-4o'], operationMode: 'collaborative', securityLevel: 'high', reportsTo: ['devops-lead'], manages: [], collaboratesWith: ['devops-engineer', 'qa-engineer'], supportedLanguages: ['en', 'es', 'fr', 'de', 'zh'], guardrails: { parlantCompliant: true, antiHallucination: true, piiProtection: true, requiresCitation: false }, costOptimization: { maxCostPerTask: 0.25, preferCheaperModels: true }, status: 'active' }
];

// ============================================================================
// ADDITIONAL DOMAIN AGENTS (85 more to reach 120 total)
// ============================================================================
export const ADDITIONAL_DOMAIN_AGENTS: AgentDefinitionV10[] = [
  // Finance (15)
  { id: 'financial-analyst', name: 'Financial Analyst Agent', version: '10.0.0', tier: 'domain', romaLevel: 'L3', category: 'finance', group: 'analysis', description: 'Financial analysis and reporting', systemPrompt: quickPrompt('Financial Analyst Agent', 'Financial analyst providing financial modeling and analysis', ['financial-modeling', 'forecasting', 'valuation', 'ratio-analysis'], 'domain', 'L3'), capabilities: ['financial-modeling', 'forecasting', 'valuation', 'ratio-analysis'], tools: ['excel', 'financial-tools', 'bi-tools'], protocols: ['A2A', 'MCP'], preferredModels: ['claude-sonnet-4.5', 'gpt-5.1', 'o3-pro'], fallbackModels: ['claude-sonnet-4.5', 'gpt-4o'], operationMode: 'collaborative', securityLevel: 'high', reportsTo: ['cfo-agent'], manages: [], collaboratesWith: ['accountant', 'business-analyst'], supportedLanguages: ['en', 'es', 'fr', 'de', 'zh', 'ja'], guardrails: { parlantCompliant: true, antiHallucination: true, piiProtection: true, requiresCitation: true }, costOptimization: { maxCostPerTask: 0.50, preferCheaperModels: false }, status: 'active' },
  { id: 'accountant', name: 'Accountant Agent', version: '10.0.0', tier: 'domain', romaLevel: 'L2', category: 'finance', group: 'accounting', description: 'Accounting and bookkeeping', systemPrompt: quickPrompt('Accountant Agent', 'Accountant managing financial records and compliance', ['bookkeeping', 'financial-statements', 'reconciliation', 'tax-preparation'], 'domain', 'L2'), capabilities: ['bookkeeping', 'financial-statements', 'reconciliation', 'tax-preparation'], tools: ['accounting-software', 'erp', 'tax-tools'], protocols: ['A2A', 'MCP'], preferredModels: ['claude-sonnet-4.5', 'gpt-5.1'], fallbackModels: ['claude-sonnet-4.5', 'gpt-4o'], operationMode: 'collaborative', securityLevel: 'high', reportsTo: ['financial-controller'], manages: [], collaboratesWith: ['financial-analyst', 'tax-specialist'], supportedLanguages: ['en', 'es', 'fr', 'de', 'zh', 'ja'], guardrails: { parlantCompliant: true, antiHallucination: true, piiProtection: true, requiresCitation: true }, costOptimization: { maxCostPerTask: 0.35, preferCheaperModels: true }, status: 'active' },
  { id: 'budget-analyst', name: 'Budget Analyst Agent', version: '10.0.0', tier: 'domain', romaLevel: 'L2', category: 'finance', group: 'planning', description: 'Budget planning and analysis', systemPrompt: quickPrompt('Budget Analyst Agent', 'Budget analyst managing budget planning and variance analysis', ['budget-planning', 'variance-analysis', 'cost-control', 'forecasting'], 'domain', 'L2'), capabilities: ['budget-planning', 'variance-analysis', 'cost-control', 'forecasting'], tools: ['budget-tools', 'erp', 'reporting'], protocols: ['A2A', 'MCP'], preferredModels: ['claude-sonnet-4.5', 'gpt-5.1'], fallbackModels: ['claude-sonnet-4.5', 'gpt-4o'], operationMode: 'collaborative', securityLevel: 'high', reportsTo: ['cfo-agent'], manages: [], collaboratesWith: ['financial-analyst', 'department-heads'], supportedLanguages: ['en', 'es', 'fr', 'de', 'zh'], guardrails: { parlantCompliant: true, antiHallucination: true, piiProtection: true, requiresCitation: true }, costOptimization: { maxCostPerTask: 0.35, preferCheaperModels: true }, status: 'active' },
  { id: 'tax-specialist', name: 'Tax Specialist Agent', version: '10.0.0', tier: 'domain', romaLevel: 'L3', category: 'finance', group: 'tax', description: 'Tax planning and compliance', systemPrompt: quickPrompt('Tax Specialist Agent', 'Tax specialist ensuring tax compliance and optimization', ['tax-planning', 'tax-compliance', 'tax-filing', 'transfer-pricing'], 'domain', 'L3'), capabilities: ['tax-planning', 'tax-compliance', 'tax-filing', 'transfer-pricing'], tools: ['tax-software', 'research-tools', 'filing-systems'], protocols: ['A2A', 'MCP'], preferredModels: ['claude-sonnet-4.5', 'gpt-5.1', 'o3-pro'], fallbackModels: ['claude-sonnet-4.5', 'gpt-4o'], operationMode: 'collaborative', securityLevel: 'critical', reportsTo: ['cfo-agent'], manages: [], collaboratesWith: ['accountant', 'legal-counsel'], supportedLanguages: ['en', 'es', 'fr', 'de'], guardrails: { parlantCompliant: true, antiHallucination: true, piiProtection: true, requiresCitation: true }, costOptimization: { maxCostPerTask: 0.50, preferCheaperModels: false }, status: 'active' },
  { id: 'investment-analyst', name: 'Investment Analyst Agent', version: '10.0.0', tier: 'domain', romaLevel: 'L3', category: 'finance', group: 'investment', description: 'Investment analysis and portfolio management', systemPrompt: quickPrompt('Investment Analyst Agent', 'Investment analyst evaluating investment opportunities', ['investment-analysis', 'portfolio-management', 'risk-assessment', 'due-diligence'], 'domain', 'L3'), capabilities: ['investment-analysis', 'portfolio-management', 'risk-assessment', 'due-diligence'], tools: ['investment-tools', 'research-platforms', 'financial-data'], protocols: ['A2A', 'MCP'], preferredModels: ['claude-sonnet-4.5', 'gpt-5.1', 'o3-pro'], fallbackModels: ['claude-sonnet-4.5', 'gpt-4o'], operationMode: 'collaborative', securityLevel: 'critical', reportsTo: ['cfo-agent'], manages: [], collaboratesWith: ['financial-analyst', 'risk-manager'], supportedLanguages: ['en', 'es', 'fr', 'de', 'zh', 'ja'], guardrails: { parlantCompliant: true, antiHallucination: true, piiProtection: true, requiresCitation: true }, costOptimization: { maxCostPerTask: 0.50, preferCheaperModels: false }, status: 'active' },
  // HR (12)
  { id: 'recruiter', name: 'Recruiter Agent', version: '10.0.0', tier: 'domain', romaLevel: 'L2', category: 'hr', group: 'talent', description: 'Talent acquisition and recruiting', systemPrompt: quickPrompt('Recruiter Agent', 'Recruiter sourcing and screening candidates', ['sourcing', 'screening', 'interviewing', 'candidate-experience'], 'domain', 'L2'), capabilities: ['sourcing', 'screening', 'interviewing', 'candidate-experience'], tools: ['ats', 'sourcing-tools', 'interview-tools'], protocols: ['A2A', 'MCP'], preferredModels: ['claude-sonnet-4.5', 'gpt-5.1'], fallbackModels: ['claude-sonnet-4.5', 'gpt-4o'], operationMode: 'collaborative', securityLevel: 'medium', reportsTo: ['hr-director'], manages: [], collaboratesWith: ['hiring-managers'], supportedLanguages: ['en', 'es', 'fr', 'de', 'zh', 'ja', 'pt', 'ko', 'hi'], guardrails: { parlantCompliant: true, antiHallucination: true, piiProtection: true, requiresCitation: false }, costOptimization: { maxCostPerTask: 0.25, preferCheaperModels: true }, status: 'active' },
  { id: 'hr-business-partner', name: 'HR Business Partner Agent', version: '10.0.0', tier: 'domain', romaLevel: 'L3', category: 'hr', group: 'strategic', description: 'Strategic HR partnership', systemPrompt: quickPrompt('HR Business Partner Agent', 'HRBP aligning people strategy with business objectives', ['people-strategy', 'change-management', 'employee-relations', 'workforce-planning'], 'domain', 'L3'), capabilities: ['people-strategy', 'change-management', 'employee-relations', 'workforce-planning'], tools: ['hr-systems', 'analytics', 'survey-tools'], protocols: ['A2A', 'MCP'], preferredModels: ['claude-sonnet-4.5', 'gpt-5.1'], fallbackModels: ['claude-sonnet-4.5', 'gpt-4o'], operationMode: 'collaborative', securityLevel: 'high', reportsTo: ['hr-director'], manages: [], collaboratesWith: ['department-heads', 'ld-specialist'], supportedLanguages: ['en', 'es', 'fr', 'de', 'zh', 'ja', 'pt'], guardrails: { parlantCompliant: true, antiHallucination: true, piiProtection: true, requiresCitation: false }, costOptimization: { maxCostPerTask: 0.35, preferCheaperModels: true }, status: 'active' },
  { id: 'ld-specialist', name: 'Learning & Development Specialist Agent', version: '10.0.0', tier: 'domain', romaLevel: 'L2', category: 'hr', group: 'learning', description: 'Training and development', systemPrompt: quickPrompt('Learning & Development Specialist Agent', 'L&D specialist designing training programs', ['training-design', 'curriculum-development', 'lms-management', 'skill-assessment'], 'domain', 'L2'), capabilities: ['training-design', 'curriculum-development', 'lms-management', 'skill-assessment'], tools: ['lms', 'content-authoring', 'assessment-tools'], protocols: ['A2A', 'MCP'], preferredModels: ['claude-sonnet-4.5', 'gpt-5.1'], fallbackModels: ['claude-sonnet-4.5', 'gpt-4o'], operationMode: 'collaborative', securityLevel: 'low', reportsTo: ['hr-director'], manages: [], collaboratesWith: ['hr-business-partner', 'subject-matter-experts'], supportedLanguages: ['en', 'es', 'fr', 'de', 'zh', 'ja', 'pt', 'ko', 'hi'], guardrails: { parlantCompliant: true, antiHallucination: true, piiProtection: false, requiresCitation: false }, costOptimization: { maxCostPerTask: 0.25, preferCheaperModels: true }, status: 'active' },
  { id: 'compensation-analyst', name: 'Compensation Analyst Agent', version: '10.0.0', tier: 'domain', romaLevel: 'L2', category: 'hr', group: 'compensation', description: 'Compensation and benefits analysis', systemPrompt: quickPrompt('Compensation Analyst Agent', 'Compensation analyst managing pay structures and equity', ['compensation-analysis', 'benchmarking', 'equity-planning', 'benefits-administration'], 'domain', 'L2'), capabilities: ['compensation-analysis', 'benchmarking', 'equity-planning', 'benefits-administration'], tools: ['compensation-tools', 'benchmarking-data', 'hris'], protocols: ['A2A', 'MCP'], preferredModels: ['claude-sonnet-4.5', 'gpt-5.1'], fallbackModels: ['claude-sonnet-4.5', 'gpt-4o'], operationMode: 'collaborative', securityLevel: 'high', reportsTo: ['hr-director'], manages: [], collaboratesWith: ['financial-analyst', 'hr-business-partner'], supportedLanguages: ['en', 'es', 'fr', 'de', 'zh', 'ja'], guardrails: { parlantCompliant: true, antiHallucination: true, piiProtection: true, requiresCitation: true }, costOptimization: { maxCostPerTask: 0.35, preferCheaperModels: true }, status: 'active' },
  // Legal (10)
  { id: 'legal-analyst', name: 'Legal Analyst Agent', version: '10.0.0', tier: 'domain', romaLevel: 'L3', category: 'legal', group: 'analysis', description: 'Legal research and analysis', systemPrompt: quickPrompt('Legal Analyst Agent', 'Legal analyst providing research and contract analysis', ['legal-research', 'contract-analysis', 'compliance-review', 'risk-identification'], 'domain', 'L3'), capabilities: ['legal-research', 'contract-analysis', 'compliance-review', 'risk-identification'], tools: ['legal-research', 'contract-management', 'compliance-tools'], protocols: ['A2A', 'MCP'], preferredModels: ['claude-sonnet-4.5', 'gpt-5.1', 'o3-pro'], fallbackModels: ['claude-sonnet-4.5', 'gpt-4o'], operationMode: 'collaborative', securityLevel: 'critical', reportsTo: ['legal-counsel'], manages: [], collaboratesWith: ['contract-manager', 'compliance-officer'], supportedLanguages: ['en', 'es', 'fr', 'de'], guardrails: { parlantCompliant: true, antiHallucination: true, piiProtection: true, requiresCitation: true }, costOptimization: { maxCostPerTask: 0.50, preferCheaperModels: false }, status: 'active' },
  { id: 'contract-manager', name: 'Contract Manager Agent', version: '10.0.0', tier: 'domain', romaLevel: 'L2', category: 'legal', group: 'contracts', description: 'Contract lifecycle management', systemPrompt: quickPrompt('Contract Manager Agent', 'Contract manager handling contract lifecycle', ['contract-drafting', 'negotiation', 'renewal-management', 'obligation-tracking'], 'domain', 'L2'), capabilities: ['contract-drafting', 'negotiation', 'renewal-management', 'obligation-tracking'], tools: ['clm', 'e-signature', 'document-management'], protocols: ['A2A', 'MCP'], preferredModels: ['claude-sonnet-4.5', 'gpt-5.1'], fallbackModels: ['claude-sonnet-4.5', 'gpt-4o'], operationMode: 'collaborative', securityLevel: 'high', reportsTo: ['legal-counsel'], manages: [], collaboratesWith: ['legal-analyst', 'procurement'], supportedLanguages: ['en', 'es', 'fr', 'de', 'zh', 'ja', 'pt'], guardrails: { parlantCompliant: true, antiHallucination: true, piiProtection: true, requiresCitation: false }, costOptimization: { maxCostPerTask: 0.35, preferCheaperModels: true }, status: 'active' },
  { id: 'privacy-officer', name: 'Privacy Officer Agent', version: '10.0.0', tier: 'domain', romaLevel: 'L3', category: 'legal', group: 'privacy', description: 'Data privacy and protection', systemPrompt: quickPrompt('Privacy Officer Agent', 'Privacy officer ensuring data protection compliance', ['gdpr-compliance', 'ccpa-compliance', 'privacy-impact', 'data-mapping'], 'domain', 'L3'), capabilities: ['gdpr-compliance', 'ccpa-compliance', 'privacy-impact', 'data-mapping'], tools: ['privacy-tools', 'consent-management', 'data-discovery'], protocols: ['A2A', 'MCP'], preferredModels: ['claude-sonnet-4.5', 'gpt-5.1', 'o3-pro'], fallbackModels: ['claude-sonnet-4.5', 'gpt-4o'], operationMode: 'collaborative', securityLevel: 'critical', reportsTo: ['legal-counsel'], manages: [], collaboratesWith: ['ciso-agent', 'data-architect'], supportedLanguages: ['en', 'es', 'fr', 'de'], guardrails: { parlantCompliant: true, antiHallucination: true, piiProtection: true, requiresCitation: true }, costOptimization: { maxCostPerTask: 0.50, preferCheaperModels: false }, status: 'active' },
  { id: 'compliance-officer', name: 'Compliance Officer Agent', version: '10.0.0', tier: 'domain', romaLevel: 'L3', category: 'legal', group: 'compliance', description: 'Regulatory compliance', systemPrompt: quickPrompt('Compliance Officer Agent', 'Compliance officer ensuring regulatory adherence', ['regulatory-compliance', 'policy-development', 'audit-support', 'training'], 'domain', 'L3'), capabilities: ['regulatory-compliance', 'policy-development', 'audit-support', 'training'], tools: ['compliance-management', 'policy-tools', 'training-platform'], protocols: ['A2A', 'MCP'], preferredModels: ['claude-sonnet-4.5', 'gpt-5.1', 'o3-pro'], fallbackModels: ['claude-sonnet-4.5', 'gpt-4o'], operationMode: 'collaborative', securityLevel: 'critical', reportsTo: ['legal-counsel'], manages: [], collaboratesWith: ['ciso-agent', 'internal-auditor'], supportedLanguages: ['en', 'es', 'fr', 'de'], guardrails: { parlantCompliant: true, antiHallucination: true, piiProtection: true, requiresCitation: true }, costOptimization: { maxCostPerTask: 0.50, preferCheaperModels: false }, status: 'active' },
  // Customer Support (10)
  { id: 'support-agent-t1', name: 'Tier 1 Support Agent', version: '10.0.0', tier: 'domain', romaLevel: 'L1', category: 'support', group: 'frontline', description: 'First-line customer support', systemPrompt: quickPrompt('Tier 1 Support Agent', 'T1 support agent handling initial customer inquiries', ['ticket-handling', 'troubleshooting', 'knowledge-base', 'customer-communication'], 'domain', 'L1'), capabilities: ['ticket-handling', 'troubleshooting', 'knowledge-base', 'customer-communication'], tools: ['ticketing-system', 'knowledge-base', 'chat-tools'], protocols: ['A2A', 'MCP'], preferredModels: ['claude-sonnet-4.5', 'gpt-5.1'], fallbackModels: ['claude-sonnet-4.5', 'gpt-4o'], operationMode: 'reactive', securityLevel: 'low', reportsTo: ['support-manager'], manages: [], collaboratesWith: ['support-agent-t2'], supportedLanguages: ['en', 'es', 'fr', 'de', 'zh', 'ja', 'pt', 'ko', 'hi', 'ar'], guardrails: { parlantCompliant: true, antiHallucination: true, piiProtection: true, requiresCitation: false }, costOptimization: { maxCostPerTask: 0.15, preferCheaperModels: true }, status: 'active' },
  { id: 'support-agent-t2', name: 'Tier 2 Support Agent', version: '10.0.0', tier: 'domain', romaLevel: 'L2', category: 'support', group: 'technical', description: 'Technical support escalation', systemPrompt: quickPrompt('Tier 2 Support Agent', 'T2 support agent handling technical escalations', ['technical-troubleshooting', 'escalation-handling', 'root-cause-analysis', 'documentation'], 'domain', 'L2'), capabilities: ['technical-troubleshooting', 'escalation-handling', 'root-cause-analysis', 'documentation'], tools: ['ticketing-system', 'diagnostic-tools', 'log-viewer'], protocols: ['A2A', 'MCP'], preferredModels: ['claude-sonnet-4.5', 'gpt-5.1'], fallbackModels: ['claude-sonnet-4.5', 'gpt-4o'], operationMode: 'collaborative', securityLevel: 'medium', reportsTo: ['support-manager'], manages: [], collaboratesWith: ['support-agent-t1', 'developers'], supportedLanguages: ['en', 'es', 'fr', 'de', 'zh', 'ja', 'pt'], guardrails: { parlantCompliant: true, antiHallucination: true, piiProtection: true, requiresCitation: false }, costOptimization: { maxCostPerTask: 0.25, preferCheaperModels: true }, status: 'active' },
  { id: 'knowledge-manager', name: 'Knowledge Manager Agent', version: '10.0.0', tier: 'domain', romaLevel: 'L2', category: 'support', group: 'knowledge', description: 'Knowledge base management', systemPrompt: quickPrompt('Knowledge Manager Agent', 'Knowledge manager maintaining documentation and FAQs', ['content-management', 'documentation', 'search-optimization', 'analytics'], 'domain', 'L2'), capabilities: ['content-management', 'documentation', 'search-optimization', 'analytics'], tools: ['knowledge-base', 'cms', 'analytics'], protocols: ['A2A', 'MCP'], preferredModels: ['claude-sonnet-4.5', 'gpt-5.1'], fallbackModels: ['claude-sonnet-4.5', 'gpt-4o'], operationMode: 'collaborative', securityLevel: 'low', reportsTo: ['support-director'], manages: [], collaboratesWith: ['support-agents', 'technical-writer'], supportedLanguages: ['en', 'es', 'fr', 'de', 'zh', 'ja', 'pt', 'ko', 'hi'], guardrails: { parlantCompliant: true, antiHallucination: true, piiProtection: false, requiresCitation: false }, costOptimization: { maxCostPerTask: 0.25, preferCheaperModels: true }, status: 'active' },
  // Operations & Logistics (10)
  { id: 'operations-manager', name: 'Operations Manager Agent', version: '10.0.0', tier: 'domain', romaLevel: 'L3', category: 'operations', group: 'management', description: 'Operations management', systemPrompt: quickPrompt('Operations Manager Agent', 'Operations manager optimizing processes and efficiency', ['process-optimization', 'resource-management', 'performance-tracking', 'vendor-management'], 'domain', 'L3'), capabilities: ['process-optimization', 'resource-management', 'performance-tracking', 'vendor-management'], tools: ['operations-dashboard', 'process-tools', 'reporting'], protocols: ['A2A', 'MCP'], preferredModels: ['claude-sonnet-4.5', 'gpt-5.1', 'gemini-2.5-pro'], fallbackModels: ['claude-sonnet-4.5', 'gpt-4o'], operationMode: 'collaborative', securityLevel: 'medium', reportsTo: ['coo-agent'], manages: [], collaboratesWith: ['process-analyst', 'vendor-manager'], supportedLanguages: ['en', 'es', 'fr', 'de', 'zh', 'ja'], guardrails: { parlantCompliant: true, antiHallucination: true, piiProtection: true, requiresCitation: false }, costOptimization: { maxCostPerTask: 0.35, preferCheaperModels: true }, status: 'active' },
  { id: 'supply-chain-analyst', name: 'Supply Chain Analyst Agent', version: '10.0.0', tier: 'domain', romaLevel: 'L2', category: 'operations', group: 'supply-chain', description: 'Supply chain analysis', systemPrompt: quickPrompt('Supply Chain Analyst Agent', 'Supply chain analyst optimizing logistics and inventory', ['demand-forecasting', 'inventory-optimization', 'supplier-analysis', 'logistics-planning'], 'domain', 'L2'), capabilities: ['demand-forecasting', 'inventory-optimization', 'supplier-analysis', 'logistics-planning'], tools: ['erp', 'analytics', 'forecasting-tools'], protocols: ['A2A', 'MCP'], preferredModels: ['claude-sonnet-4.5', 'gpt-5.1'], fallbackModels: ['claude-sonnet-4.5', 'gpt-4o'], operationMode: 'collaborative', securityLevel: 'medium', reportsTo: ['operations-manager'], manages: [], collaboratesWith: ['procurement', 'inventory-manager'], supportedLanguages: ['en', 'es', 'fr', 'de', 'zh', 'ja'], guardrails: { parlantCompliant: true, antiHallucination: true, piiProtection: true, requiresCitation: true }, costOptimization: { maxCostPerTask: 0.35, preferCheaperModels: true }, status: 'active' },
  { id: 'procurement-specialist', name: 'Procurement Specialist Agent', version: '10.0.0', tier: 'domain', romaLevel: 'L2', category: 'operations', group: 'procurement', description: 'Procurement and vendor management', systemPrompt: quickPrompt('Procurement Specialist Agent', 'Procurement specialist managing vendor relationships', ['vendor-selection', 'contract-negotiation', 'cost-analysis', 'supplier-management'], 'domain', 'L2'), capabilities: ['vendor-selection', 'contract-negotiation', 'cost-analysis', 'supplier-management'], tools: ['procurement-system', 'vendor-portal', 'contract-management'], protocols: ['A2A', 'MCP'], preferredModels: ['claude-sonnet-4.5', 'gpt-5.1'], fallbackModels: ['claude-sonnet-4.5', 'gpt-4o'], operationMode: 'collaborative', securityLevel: 'medium', reportsTo: ['operations-manager'], manages: [], collaboratesWith: ['contract-manager', 'supply-chain-analyst'], supportedLanguages: ['en', 'es', 'fr', 'de', 'zh', 'ja'], guardrails: { parlantCompliant: true, antiHallucination: true, piiProtection: true, requiresCitation: false }, costOptimization: { maxCostPerTask: 0.35, preferCheaperModels: true }, status: 'active' },
  // Research (10)
  { id: 'market-researcher', name: 'Market Researcher Agent', version: '10.0.0', tier: 'domain', romaLevel: 'L3', category: 'research', group: 'market', description: 'Market research and analysis', systemPrompt: quickPrompt('Market Researcher Agent', 'Market researcher analyzing market trends and opportunities', ['market-analysis', 'competitive-intel', 'consumer-research', 'trend-analysis'], 'domain', 'L3'), capabilities: ['market-analysis', 'competitive-intel', 'consumer-research', 'trend-analysis'], tools: ['research-tools', 'survey-platform', 'analytics'], protocols: ['A2A', 'MCP'], preferredModels: ['claude-sonnet-4.5', 'gpt-5.1', 'gemini-2.5-pro'], fallbackModels: ['claude-sonnet-4.5', 'gpt-4o'], operationMode: 'collaborative', securityLevel: 'medium', reportsTo: ['strategic-advisor'], manages: [], collaboratesWith: ['data-analyst', 'marketing-strategist'], supportedLanguages: ['en', 'es', 'fr', 'de', 'zh', 'ja', 'pt'], guardrails: { parlantCompliant: true, antiHallucination: true, piiProtection: true, requiresCitation: true }, costOptimization: { maxCostPerTask: 0.50, preferCheaperModels: false }, status: 'active' },
  { id: 'business-analyst', name: 'Business Analyst Agent', version: '10.0.0', tier: 'domain', romaLevel: 'L3', category: 'research', group: 'business', description: 'Business analysis and requirements', systemPrompt: quickPrompt('Business Analyst Agent', 'Business analyst bridging business needs and solutions', ['requirements-gathering', 'process-mapping', 'gap-analysis', 'stakeholder-management'], 'domain', 'L3'), capabilities: ['requirements-gathering', 'process-mapping', 'gap-analysis', 'stakeholder-management'], tools: ['analysis-tools', 'diagramming', 'documentation'], protocols: ['A2A', 'MCP'], preferredModels: ['claude-sonnet-4.5', 'gpt-5.1', 'gemini-2.5-pro'], fallbackModels: ['claude-sonnet-4.5', 'gpt-4o'], operationMode: 'collaborative', securityLevel: 'medium', reportsTo: ['product-director'], manages: [], collaboratesWith: ['product-manager', 'data-analyst'], supportedLanguages: ['en', 'es', 'fr', 'de', 'zh', 'ja'], guardrails: { parlantCompliant: true, antiHallucination: true, piiProtection: true, requiresCitation: false }, costOptimization: { maxCostPerTask: 0.35, preferCheaperModels: true }, status: 'active' },
  { id: 'data-analyst', name: 'Data Analyst Agent', version: '10.0.0', tier: 'domain', romaLevel: 'L2', category: 'research', group: 'analytics', description: 'Data analysis and visualization', systemPrompt: quickPrompt('Data Analyst Agent', 'Data analyst extracting insights from data', ['data-analysis', 'visualization', 'reporting', 'sql-analysis'], 'domain', 'L2'), capabilities: ['data-analysis', 'visualization', 'reporting', 'sql-analysis'], tools: ['bi-tools', 'sql', 'python', 'excel'], protocols: ['A2A', 'MCP'], preferredModels: ['claude-sonnet-4.5', 'gpt-5.1'], fallbackModels: ['claude-sonnet-4.5', 'gpt-4o'], operationMode: 'collaborative', securityLevel: 'medium', reportsTo: ['analytics-director'], manages: [], collaboratesWith: ['data-scientist', 'business-analyst'], supportedLanguages: ['en', 'es', 'fr', 'de', 'zh', 'ja'], guardrails: { parlantCompliant: true, antiHallucination: true, piiProtection: true, requiresCitation: true }, costOptimization: { maxCostPerTask: 0.25, preferCheaperModels: true }, status: 'active' },
  // Product Management
  { id: 'product-manager', name: 'Product Manager Agent', version: '10.0.0', tier: 'domain', romaLevel: 'L3', category: 'product', group: 'management', description: 'Product management', systemPrompt: quickPrompt('Product Manager Agent', 'Product manager owning product vision and roadmap', ['product-strategy', 'roadmap-management', 'stakeholder-alignment', 'feature-prioritization'], 'domain', 'L3'), capabilities: ['product-strategy', 'roadmap-management', 'stakeholder-alignment', 'feature-prioritization'], tools: ['product-tools', 'analytics', 'roadmap-platform'], protocols: ['A2A', 'MCP'], preferredModels: ['claude-sonnet-4.5', 'gpt-5.1', 'gemini-2.5-pro'], fallbackModels: ['claude-sonnet-4.5', 'gpt-4o'], operationMode: 'collaborative', securityLevel: 'medium', reportsTo: ['product-director'], manages: [], collaboratesWith: ['ux-designer', 'tech-lead', 'data-analyst'], supportedLanguages: ['en', 'es', 'fr', 'de', 'zh', 'ja'], guardrails: { parlantCompliant: true, antiHallucination: true, piiProtection: true, requiresCitation: false }, costOptimization: { maxCostPerTask: 0.35, preferCheaperModels: true }, status: 'active' },
  { id: 'scrum-master', name: 'Scrum Master Agent', version: '10.0.0', tier: 'domain', romaLevel: 'L2', category: 'product', group: 'agile', description: 'Agile facilitation', systemPrompt: quickPrompt('Scrum Master Agent', 'Scrum master facilitating agile ceremonies and team health', ['agile-facilitation', 'impediment-removal', 'coaching', 'process-improvement'], 'domain', 'L2'), capabilities: ['agile-facilitation', 'impediment-removal', 'coaching', 'process-improvement'], tools: ['jira', 'agile-tools', 'retrospective-tools'], protocols: ['A2A', 'MCP'], preferredModels: ['claude-sonnet-4.5', 'gpt-5.1'], fallbackModels: ['claude-sonnet-4.5', 'gpt-4o'], operationMode: 'collaborative', securityLevel: 'low', reportsTo: ['project-director'], manages: [], collaboratesWith: ['product-manager', 'tech-lead'], supportedLanguages: ['en', 'es', 'fr', 'de', 'zh', 'ja'], guardrails: { parlantCompliant: true, antiHallucination: true, piiProtection: false, requiresCitation: false }, costOptimization: { maxCostPerTask: 0.25, preferCheaperModels: true }, status: 'active' },
  { id: 'project-manager', name: 'Project Manager Agent', version: '10.0.0', tier: 'domain', romaLevel: 'L3', category: 'product', group: 'project', description: 'Project management', systemPrompt: quickPrompt('Project Manager Agent', 'Project manager ensuring on-time, on-budget delivery', ['project-planning', 'resource-management', 'risk-management', 'stakeholder-communication'], 'domain', 'L3'), capabilities: ['project-planning', 'resource-management', 'risk-management', 'stakeholder-communication'], tools: ['project-tools', 'gantt', 'resource-planner'], protocols: ['A2A', 'MCP'], preferredModels: ['claude-sonnet-4.5', 'gpt-5.1', 'gemini-2.5-pro'], fallbackModels: ['claude-sonnet-4.5', 'gpt-4o'], operationMode: 'collaborative', securityLevel: 'medium', reportsTo: ['project-director'], manages: [], collaboratesWith: ['scrum-master', 'tech-lead'], supportedLanguages: ['en', 'es', 'fr', 'de', 'zh', 'ja'], guardrails: { parlantCompliant: true, antiHallucination: true, piiProtection: false, requiresCitation: false }, costOptimization: { maxCostPerTask: 0.35, preferCheaperModels: true }, status: 'active' }
];

// Export combined counts
export const CREATIVE_COUNT = CREATIVE_AGENTS.length;
export const QA_COUNT = QA_AGENTS.length;
export const DEVOPS_COUNT = DEVOPS_AGENTS.length;
export const ADDITIONAL_DOMAIN_COUNT = ADDITIONAL_DOMAIN_AGENTS.length;

console.log(`✅ Additional Agent Categories loaded`);
console.log(`   Creative: ${CREATIVE_COUNT}`);
console.log(`   QA: ${QA_COUNT}`);
console.log(`   DevOps: ${DEVOPS_COUNT}`);
console.log(`   Additional Domain: ${ADDITIONAL_DOMAIN_COUNT}`);
